version: '3'

services:
  jenkins-blueocean:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ./vendor:/var/jenkins_home/workspace/OWS_pipeline_1_main/vendor
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

  docker:
    image: docker:dind
    container_name: docker
    restart: 'no'
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      - jenkins

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - jenkins

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    ports:
      - "3306:3306"
    networks:
      - website
      - jenkins

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./website:/var/www/html/website
      - ./vendor:/var/www/html/vendor
    ports:
      - "8000:80"
    networks:
      - website

  phpunit:
    image: php:8.3.4
    container_name: phpunit
    command: ["php", "./vendor/bin/phpunit"]
    restart: 'no'
    volumes:
      - ./vendor:/vendor
      - ./website:/website
      - ./phpunit.xml:/phpunit.xml
      - ./tests:/tests
    depends_on:
      - php
    networks:
      - website


volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
    external: true
  website:
